# Generated by Django 3.2.6 on 2021-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='volume',
            field=models.CharField(max_length=20),
        ),
    ]
